# Setup function to resolve scripts with node for hoisting
def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

# Include the necessary scripts for React Native and Permissions setup
node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, min_ios_version_supported

# Prepare React Native project
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
#   },
# };
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

# Optional: Framework linkage configuration
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'ViroStarterKit' do
  config = use_native_modules!

  # React Native integration
  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Include ViroReact and ViroKit pods
  pod 'ViroReact', :path => '../node_modules/@reactvision/react-viro/ios/'
  pod 'ViroKit', :path => '../node_modules/@reactvision/react-viro/ios/dist/ViroRenderer/'

  # Call the permissions setup with the permissions you want to include
  setup_permissions([
    # Uncomment the permissions you want to include
    'Camera',
    # 'Microphone',
    # 'LocationWhenInUse',
    'PhotoLibrary',
    # 'Notifications',
    # Add other permissions you need
    # 'Bluetooth',
    # 'FaceID',
    # 'MediaLibrary',
    # 'Contacts',
    # 'AppTrackingTransparency',
  ])

  # Test target
  target 'ViroStarterKitTests' do
    inherit! :complete
    # Pods for testing
  end

  # Post install hook to ensure proper setup for React Native
  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
